DROP TABLE IF EXISTS COURSES ;
CREATE TABLE COURSES (
    COURSE_ID INT,
    COURSE_NAME CHAR(36),

    PRIMARY KEY (COURSE_ID)
);

INSERT INTO COURSES (COURSE_ID, COURSE_NAME)
SELECT generate_series(1, 100000), gen_random_uuid();

-- Pagination with seek pattern
EXPLAIN ANALYZE SELECT COURSE_ID, COURSE_NAME
FROM COURSES
WHERE (COURSE_ID) > 1000
ORDER BY COURSE_ID
LIMIT 1000;

EXPLAIN ANALYZE SELECT COURSE_ID, COURSE_NAME
FROM COURSES
WHERE (COURSE_ID) > 5000
ORDER BY COURSE_ID
LIMIT 1000;

-- Pagination with FETCH clause
EXPLAIN ANALYZE SELECT COURSE_ID, COURSE_NAME
FROM COURSES
WHERE (COURSE_ID) > 1000
ORDER BY COURSE_ID
FETCH FIRST 1000 ROWS ONLY;

EXPLAIN ANALYZE SELECT COURSE_ID, COURSE_NAME
FROM COURSES
WHERE (COURSE_ID) > 5000
ORDER BY COURSE_ID
FETCH FIRST 1000 ROWS ONLY;

-- Pagination with OFFSET clause
EXPLAIN ANALYZE SELECT COURSE_ID, COURSE_NAME
FROM COURSES
ORDER BY COURSE_ID
OFFSET 1000 LIMIT 1000;

EXPLAIN ANALYZE SELECT COURSE_ID, COURSE_NAME
FROM COURSES
ORDER BY COURSE_ID
OFFSET 5000 LIMIT 1000;

