DROP TABLE IF EXISTS COURSES;
CREATE TABLE COURSES
(
    COURSE_ID   INT,
    COURSE_NAME CHAR(36),

    PRIMARY KEY (COURSE_ID)
);

INSERT INTO COURSES (COURSE_ID, COURSE_NAME)
SELECT generate_series(1, 100000), gen_random_uuid();

EXPLAIN ANALYZE
SELECT COURSE_ID, COURSE_NAME
FROM COURSES
WHERE (COURSE_ID) > 1000
ORDER BY COURSE_ID
    FETCH FIRST 1000 ROWS ONLY;

EXPLAIN ANALYZE
SELECT COURSE_ID, COURSE_NAME
FROM COURSES
WHERE (COURSE_ID) > 5000
ORDER BY COURSE_ID
    FETCH FIRST 1000 ROWS ONLY;
