DROP TABLE IF EXISTS COURSES;
CREATE TABLE COURSES
(
    COURSE_ID   INT,
    COURSE_NAME CHAR(36),

    PRIMARY KEY (COURSE_ID)
);

INSERT INTO COURSES (COURSE_ID, COURSE_NAME)
SELECT generate_series(1, 100000), gen_random_uuid();

EXPLAIN ANALYZE
SELECT COURSE_ID, COURSE_NAME
FROM COURSES
ORDER BY COURSE_ID
OFFSET 1000 LIMIT 1000;

EXPLAIN ANALYZE
SELECT COURSE_ID, COURSE_NAME
FROM COURSES
ORDER BY COURSE_ID
OFFSET 5000 LIMIT 1000;
